### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dmcclean** [ramsdell/agum#2]
Do you think you might be willing to switch to a more permissive license? I'm collaborating on the dimensional-dk package trying to make a great next generation units library. The relationship to your library is that really advanced uses of the library, especially for linear algebra, run in to limitations where GHC's type checker can't prove that 1/(1/x) = x in the Abelian group of physical dimensions under multiplication, and similar "trivial" facts. I'm interested in trying to use the new type checker plugin feature to fix this; I need to do a lot of reading first. Right now dimensional-dk is BSD3, and so are a bunch of other things downstream from there.

If not, I totally understand, it's not my intent to reopen the religious war of which open source license is best. :)

**Comment by ramsdell** [comment]
You can use essentially the same code under a BSD style license.  You can extract it from the CPSA,Diffie-Hellman.Algebra module in CPSA.  The agum program was written when I started working on Diffie-Hellman.  It was my model for dealing with exponents.  I decided to share it as a strand alone program for the fun of it.  My experiments with a Commutative Monoids was another experiment on exponents.

**Comment by dmcclean** [comment]
Cool, thanks. :)  I will see what I can do about understanding that. Cryptography is something that I know nothing about.
